CREATE TABLE VACANCY (
VCY_ID NUMBER(10),
VCY_CLOSIN DATE,
VCY_CONTRACT NUMBER(10),
VCY_DESCRIPTION VARCHAR2(255 CHAR),
VCY_SAL_MAX FLOAT(126),
VCY_SAL_MIN FLOAT(126),
VCY_OPENN DATE,
VCY_TITLE VARCHAR2(255 CHAR),
ADRESS_ADR_ID NUMBER(10),
COMPANY_CPY_ID NUMBER(10),
ID_USER NUMBER(10)
);